config/routes.rb
Ruthieonart::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :passwords, :registrations, :confirmations, :unlocks]

  devise_scope :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session

    post 'update-password' => 'devise/passwords#create', :as => :user_password
    get 'reset-password' => 'devise/passwords#new', :as => :new_user_password
    get 'update-password' => 'devise/passwords#edit', :as => :edit_user_password
    put 'update-password' => 'devise/passwords#update'
  end

  get '/contact' => 'contact#new', :as => :contact

  post '/contact' => 'contact#create'

  resources :pages, :only => [:show]

  resources :posts, :only => [:show]

  get '/posts.rss' => 'posts#index', :format => :rss

  get '/sitemap.xml' => 'sitemap#index', :as => :sitemap, :format => :xml

  authenticate :user do
    namespace :admin do
      root :to => 'admin#index'

      resource :account, :only => [:show, :edit, :update]

      resources :pages

      resources :pictures do
        collection do
          get :selector
        end
      end

      resources :posts

      resources :users

      get '/tags.json' => 'tags#index'
    end

    post 'versions/:id/revert' => 'versions#revert', :as => :revert_version
  end

  root :to => 'posts#index'

  get ':id' => 'pages#show'
end

app/views/admin/pages/_form.html.erb
<h2><%= t("pages.#{@page.persisted? ? 'edit' : 'new'}.title") %></h2>
<%= simple_form_for [:admin, @page], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= picture_inserter '#page_body-editor' %>
  <%= f.input :body do %>
    <%= f.text_area :body, :style => 'display: none;' %>
    <div id="page_body-editor" class="ace-editor" data-mode="html"></div>
  <% end %>
  <%= f.input :style do %>
    <%= f.text_area :style, :style => 'display: none;' %>
    <div id="page_style-editor" class="ace-editor" data-mode="css"></div>
  <% end %>
  <%= f.input :meta_description, :input_html => { :rows => 2 } %>
  <%= f.input :meta_keywords, :input_html => { :rows => 2 } %>
  <%= f.input :order %>
  <%= f.input :show_in_menu %>
  <%= f.input :visible %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= link_to t('pages.links.back_to_index'), admin_pages_path, :class => 'btn btn-default' %>
      <%= f.button :submit, 'Submit', :class => 'btn btn-primary' %>
      <% unless @page.persisted? %>
        <label for="redirect_to_new">
          <%= check_box_tag 'redirect_to_new', 1, true %> <%= t('helpers.submit.page.redirect_to_new') %>
        </label>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<div id="edit-page" class="admin-content">
  <%= render 'form' %>
</div>

app/views/admin/pages/index.html.erb
<div id="pages" class="admin-content">
  <h2>
    <%= t('activerecord.models.page').pluralize %>
  </h2>
  <div class="well">
    <%= search_form_for @search, :url => admin_pages_path, :html => { :method => :get, :class => 'form-inline' } do |f| %>
      <div class="form-group">
        <%= f.text_field :title_cont, :class => 'form-control', :placeholder => t('activerecord.attributes.page.title') %>
      </div>
      <div class="form-group">
        <%= f.text_field :body_or_style_cont, :class => 'form-control', :placeholder => "#{t('activerecord.attributes.page.body')} #{t('or')} #{t('activerecord.attributes.page.style')}" %>
      </div>
      <%= f.button '<span class="glyphicon glyphicon-search"></span> Search'.html_safe, :type => :submit, :class => 'btn btn-primary' %>
      <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, admin_pages_path, :class => 'btn btn-default', :rel => 'tooltip', :title => t('clear_search') %>
    <% end %>
  </div>
  <% if can? :create, Page %>
    <div class="clearfix">
      <%= link_to t('pages.new.title'), new_admin_page_path, :class => 'btn btn-primary pull-right' %>
    </div>
  <% end %>
  <% if @pages.any? %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th><%= sort_link @search, :title %></th>
            <th><%= sort_link @search, :slug %></th>
            <th><%= sort_link @search, :created_at %></th>
            <% if can? :edit, Page %><th class="icon">&nbsp;</th><% end %>
            <% if can? :destroy, Page %><th class="icon">&nbsp;</th><% end %>
          </tr>
        </thead>
        <tbody>
          <% @pages.each do |page| %>
            <tr>
              <td><%= link_to truncate(page.title, :length => 32), admin_page_path(page) %></td>
              <td><%= truncate(page.slug, :length => 32) %> <%= link_to '<span class="glyphicon glyphicon-share"></span>'.html_safe, "/#{page.slug}", :target => '_blank' %></td>
              <td><%= page.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <% if can? :edit, Page %><td class="icon"><%= icon_edit_link edit_admin_page_path(page) %></td><% end %>
              <% if can? :destroy, Page %><td class="icon"><%= icon_delete_link admin_page_path(page) %></td><% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @pages %>
  <% else %>
    <p class="lead"><%= t('messages.pages.none') %></p>
  <% end %>
</div>

app/views/admin/pages/new.html.erb
<div id="new-page" class="admin-content">
  <%= render 'form' %>
</div>

app/views/admin/pages/show.html.erb
<div id="page-<%= @page.id %>" class="admin-content">
  <h2><%= t('pages.show.title') %> <small><%= truncate(@page.title, :length => 48) %></small></h2>
  <div class="clearfix">
    <%= link_to t('pages.links.back_to_index'), admin_pages_path, :class => 'btn btn-default' %>
    <% if can? :edit, Page %><%= link_to t('pages.edit.title'), edit_admin_page_path(@page), :class => 'btn btn-primary' %><% end %>
    <% if can? :destroy, Page %><%= link_to t('pages.delete.title'), admin_page_path(@page), :method => 'delete', :class => 'btn btn-danger', :data => { :confirm => t('confirm_delete') } %><% end %>
  </div>
  <h3><%= t('pages.sections.information') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.title') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.title %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.slug') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.slug %> <%= link_to '<span class="glyphicon glyphicon-share"></span>'.html_safe, "/#{@page.slug}", :target => '_blank' %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.body') %></th>
          <td class="col-xs-8 col-sm-10"><% if @page.body.present? %><pre><%= @page.body %></pre><% else %>&nbsp;<% end %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.style') %></th>
          <td class="col-xs-8 col-sm-10"><% if @page.style.present? %><pre><%= @page.style %></pre><% else %>&nbsp;<% end %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.meta_description') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.meta_description %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.meta_keywords') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.meta_keywords %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.order') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.order %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.show_in_menu') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.show_in_menu ? t('yes') : t('no') %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.visible') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.visible ? t('yes') : t('no') %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.created_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.page.updated_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @page.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="clearfix">
    <%= link_to t('pages.links.back_to_index'), admin_pages_path, :class => 'btn btn-default' %>
    <% if can? :edit, Page %><%= link_to t('pages.edit.title'), edit_admin_page_path(@page), :class => 'btn btn-primary' %><% end %>
    <% if can? :destroy, Page %><%= link_to t('pages.delete.title'), admin_page_path(@page), :method => 'delete', :class => 'btn btn-danger', :data => { :confirm => t('confirm_delete') } %><% end %>
  </div>
</div>