config/routes.rb
Ruthieonart::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :passwords, :registrations, :confirmations, :unlocks]

  devise_scope :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session

    post 'update-password' => 'devise/passwords#create', :as => :user_password
    get 'reset-password' => 'devise/passwords#new', :as => :new_user_password
    get 'update-password' => 'devise/passwords#edit', :as => :edit_user_password
    put 'update-password' => 'devise/passwords#update'
  end

  get '/contact' => 'contact#new', :as => :contact

  post '/contact' => 'contact#create'

  resources :pages, :only => [:show]

  resources :posts, :only => [:show]

  get '/posts.rss' => 'posts#index', :format => :rss

  get '/sitemap.xml' => 'sitemap#index', :as => :sitemap, :format => :xml

  authenticate :user do
    namespace :admin do
      root :to => 'admin#index'

      resource :account, :only => [:show, :edit, :update]

      resources :pages

      resources :pictures do
        collection do
          get :selector
        end
      end

      resources :posts

      resources :users

      get '/tags.json' => 'tags#index'
    end

    post 'versions/:id/revert' => 'versions#revert', :as => :revert_version
  end

  root :to => 'posts#index'

  get ':id' => 'pages#show'
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::AdminController
  before_filter :authenticate_user!

  def show
    @account = current_user
  end

  def edit
    @account = current_user
  end

  def update
    @account = current_user

    params[:account].delete(:role) if params[:account]

    if @account.update_attributes(params[:account])
      sign_in(@account, :bypass => true)

      flash[:success] = t('messages.accounts.updated')

      redirect_to admin_account_path
    else
      flash[:error] = @account.errors.full_messages.uniq.join('. ') + '.'

      render 'edit'
    end
  end
end

app/views/admin/accounts/edit.html.erb
<div id="edit-account" class="admin-content">
  <h2><%= t('accounts.edit.title') %> <small>(<%= @account.email %>)</small></h2>
  <%= simple_form_for @account, :as => :accounts, :url => admin_account_path, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= link_to t('accounts.links.back_to_account'), admin_account_path, :class => 'btn btn-default' %>
        <%= f.button :submit, t('accounts.update.title'), :class => 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/accounts/show.html.erb
<div id="show-account" class="admin-content">
  <h2><%= t('accounts.show.title') %> <small><%= @account.email %></small></h2>
  <h3><%= t('users.sections.contact_information') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.first_name') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.first_name %></td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.last_name') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.last_name %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <h3><%= t('users.sections.account_information') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.email') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.email %></td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.created_at') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.updated_at') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <h3><%= t('users.sections.login_activity') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.sign_in_count') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.sign_in_count %></td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.current_sign_in_at') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.current_sign_in_at.blank? ? t('na') : @account.current_sign_in_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.last_sign_in_at') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.last_sign_in_at.blank? ? t('na') : @account.last_sign_in_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.current_sign_in_ip') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.current_sign_in_ip.blank? ? t('na') : @account.current_sign_in_ip %></td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.last_sign_in_ip') %></th>
        <td class="col-xs-8 col-sm-10"><%= @account.last_sign_in_ip.blank? ? t('na') : @account.last_sign_in_ip %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <div class="form-actions">
    <%= link_to t('back'), admin_root_path, :class => 'btn' %>
    <%= link_to t('accounts.edit.title'), edit_admin_account_path, :class => 'btn btn-primary' %>
  </div>
</div>