config/routes.rb
Ruthieonart::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :passwords, :registrations, :confirmations, :unlocks]

  devise_scope :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session

    post 'update-password' => 'devise/passwords#create', :as => :user_password
    get 'reset-password' => 'devise/passwords#new', :as => :new_user_password
    get 'update-password' => 'devise/passwords#edit', :as => :edit_user_password
    put 'update-password' => 'devise/passwords#update'
  end

  get '/contact' => 'contact#new', :as => :contact

  post '/contact' => 'contact#create'

  resources :pages, :only => [:show]

  resources :posts, :only => [:show]

  get '/posts.rss' => 'posts#index', :format => :rss

  get '/sitemap.xml' => 'sitemap#index', :as => :sitemap, :format => :xml

  authenticate :user do
    namespace :admin do
      root :to => 'admin#index'

      resource :account, :only => [:show, :edit, :update]

      resources :pages

      resources :pictures do
        collection do
          get :selector
        end
      end

      resources :posts

      resources :users

      get '/tags.json' => 'tags#index'
    end

    post 'versions/:id/revert' => 'versions#revert', :as => :revert_version
  end

  root :to => 'posts#index'

  get ':id' => 'pages#show'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :title, :alt_text, :caption, :image

  has_attached_file :image, { :convert_options => { :thumb => '-quality 75 -strip', :medium => '-quality 85 -strip' },
                              :path => ":rails_root/public/uploads/#{Rails.env.test? ? 'test/' : ''}:class_singular/:attachment/:style_prefix:basename.:extension",
                              :styles => { :thumb => '100x100', :medium => '300x300' },
                              :url => "/uploads/:class_singular/:attachment/#{Rails.env.test? ? 'test/' : ''}:style_prefix:basename.:extension" }

  validates_length_of   :title, :maximum => 65535
  validates_presence_of :title

  validates_length_of :alt_text, :maximum => 65535

  validates_length_of :caption, :maximum => 65535

  validates_uniqueness_of :image_fingerprint, :if => Proc.new { !Rails.env.test? }

  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 1024.megabytes
  validates_attachment_content_type :image, :content_type => %w(image/gif image/jpeg image/jpg image/pjpeg image/png image/svg+xml image/tiff image/x-png)

  after_initialize do
    if self.new_record?
      self.title ||= ''
      self.alt_text ||= ''
      self.caption ||= ''
      self.image_original_width ||= 1
      self.image_original_height ||= 1
      self.image_medium_width ||= 1
      self.image_medium_height ||= 1
      self.image_thumb_width ||= 1
      self.image_thumb_height ||= 1
    end
  end

  before_validation :modify_image_file_name
  before_validation :set_default_title

  before_post_process :image?
  after_post_process :save_image_dimensions

  protected

  def modify_image_file_name
    if image.file?
      if image.dirty?
        current_time = Time.now

        basename = "#{current_time.to_i}#{current_time.usec}".ljust(16, '0')

        extension = File.extname(self.image_file_name).downcase

        if extension == '.jpeg'
          extension = '.jpg'
        end

        if extension == '.tif'
          extension = '.tiff'
        end

        self.image.instance_write :file_name, "#{basename}#{extension}"
      end
    end
  end

  def set_default_title
    self.title = File.basename(self.image_file_name, '.*').to_s if self.title.blank? && !self.image_file_name.blank?
  end

  def image?
    self.errors.add :image, 'is not an image'

    !(image_content_type =~ /^image.*/).nil?
  end

  def save_image_dimensions
    original_geometry = Paperclip::Geometry.from_file(image.queued_for_write[:original])
    self.image_original_width = original_geometry.width
    self.image_original_height = original_geometry.height

    medium_geometry = Paperclip::Geometry.from_file(image.queued_for_write[:medium])
    self.image_medium_width = medium_geometry.width
    self.image_medium_height = medium_geometry.height

    thumb_geometry = Paperclip::Geometry.from_file(image.queued_for_write[:thumb])
    self.image_thumb_width = thumb_geometry.width
    self.image_thumb_height = thumb_geometry.height
  end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < Admin::AdminController
  before_filter :authenticate_user!

  authorize_resource

  def index
    @search = Picture.search(params[:q])

    @pictures = @search.result.page(params[:page]).per(25).order('`pictures`.`created_at` DESC')
  end

  def show
    @picture = Picture.where(:id => params[:id]).first

    if @picture.nil?
      flash[:error] = t('messages.pictures.could_not_find')

      redirect_to admin_pictures_url
    end
  end

  def new
    @picture = Picture.new
  end

  def create
    respond_to do |format|
      format.html {
        @picture = Picture.new(params[:picture])

        if @picture.save
          flash[:success] = t('messages.pictures.created')

          if params[:redirect_to_new].present?
            redirect_to new_admin_picture_url
          else
            redirect_to admin_pictures_url
          end
        else
          flash[:error] = @picture.errors.full_messages.uniq.join('. ') + '.'

          render 'new'
        end
      }
      format.js {
        @picture = Picture.create(params[:picture])
      }
    end
  end

  def edit
    @picture = Picture.where(:id => params[:id]).first

    if @picture.nil?
      flash[:error] = t('messages.pictures.could_not_find')

      redirect_to admin_pictures_url
    end
  end

  def update
    @picture = Picture.where(:id => params[:id]).first

    if @picture.nil?
      flash[:error] = t('messages.pictures.could_not_find')

      redirect_to admin_pictures_url and return
    end

    if @picture.update_attributes(params[:picture])
      flash[:success] = t('messages.pictures.updated')

      redirect_to edit_admin_picture_url(@picture)
    else
      flash[:error] = @picture.errors.full_messages.uniq.join('. ') + '.'

      render 'edit'
    end
  end

  def destroy
    @picture = Picture.where(:id => params[:id]).first

    if @picture.nil?
      flash[:error] = t('messages.pictures.could_not_find')

      redirect_to admin_pictures_url and return
    end

    @picture.destroy

    flash[:success] = t('messages.pictures.deleted')

    redirect_to admin_pictures_url
  end

  def selector
    @pictures = Picture.order('`pictures`.`created_at` DESC')

    render :layout => false
  end
end

app/helpers/admin/pictures_helper.rb
module Admin::PicturesHelper
end

app/views/admin/pictures/_form.html.erb
<h2><%= t("pictures.#{@picture.persisted? ? 'edit' : 'new'}.title") %></h2>
<%= simple_form_for [:admin, @picture], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title, :as => :string %>
  <%= f.input :alt_text, :as => :string %>
  <%= f.input :caption %>
  <%= f.input :image, :as => :file %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= link_to t('pictures.links.back_to_index'), admin_pictures_path, :class => 'btn btn-default' %>
      <%= f.button :submit, 'Submit', :class => 'btn btn-primary' %>
      <% unless @picture.persisted? %>
        <label for="redirect_to_new">
          <%= check_box_tag 'redirect_to_new', 1, true %> <%= t('helpers.submit.picture.redirect_to_new') %>
        </label>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/pictures/_picture.html.erb
<tr>
  <td style="text-align: center;"><%= link_to image_tag(@picture.image.url(:thumb), :style => 'max-height: 50px;'), admin_picture_path(picture) %></td>
  <td><%= link_to truncate(@picture.title, :length => 32), admin_picture_path(@picture) %></td>
  <td><%= @picture.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
  <% if can? :edit, Picture %><td class="icon"><%= icon_edit_link edit_admin_picture_path(@picture) %></td><% end %>
  <% if can? :destroy, Picture %><td class="icon"><%= icon_delete_link admin_picture_path(@picture) %></td><% end %>
</tr>

app/views/admin/pictures/create.js.erb
<% if @picture.new_record? %>
  alert("Failed to upload picture: <%= j @picture.errors.full_messages.join(', ').html_safe %>.");
<% else %>
  $("#pictures table").removeClass("hidden");

  $("#pictures .lead").remove();

  $("#pictures table tbody").prepend("<%= j render(@picture) %>");
<% end %>

app/views/admin/pictures/edit.html.erb
<div id="edit-picture" class="admin-content">
  <%= render 'form' %>
</div>

app/views/admin/pictures/index.html.erb
<div id="pictures" class="admin-content">
  <h2>
    <%= t('activerecord.models.picture').pluralize %>
  </h2>
  <div class="well">
    <%= search_form_for @search, :url => admin_pictures_path, :html => { :method => :get, :class => 'form-inline' } do |f| %>
      <div class="form-group">
        <%= f.text_field :title_cont, :class => 'form-control', :placeholder => t('activerecord.attributes.picture.title') %>
      </div>
      <div class="form-group">
        <%= f.text_field :alt_text_cont, :class => 'form-control', :placeholder => t('activerecord.attributes.picture.alt_text') %>
      </div>
      <div class="form-group">
        <%= f.text_field :caption_cont, :class => 'form-control', :placeholder => t('activerecord.attributes.picture.caption') %>
      </div>
      <%= f.button '<span class="glyphicon glyphicon-search"></span> Search'.html_safe, :type => :submit, :class => 'btn btn-primary' %>
      <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, admin_pictures_path, :class => 'btn btn-default', :rel => 'tooltip', :title => t('clear_search') %>
    <% end %>
  </div>
  <% if can? :create, Picture %>
    <div class="clearfix">
      <%= link_to t('pictures.new.title'), new_admin_picture_path, :class => 'btn btn-primary pull-right' %>
    </div>
  <% end %>
  <%= form_for [:admin, Picture.new], :html => { :data => { :accept => 'gif|jpe?g|png' } } do |f| %>
    <%= f.file_field :image, :name => 'picture[image]', :class => 'hidden' %>
  <% end %>
  <% if @pictures.any? %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Thumbnail</th>
            <th><%= sort_link @search, :title %></th>
            <th><%= sort_link @search, :created_at %></th>
            <% if can? :edit, Picture %><th class="icon">&nbsp;</th><% end %>
            <% if can? :destroy, Picture %><th class="icon">&nbsp;</th><% end %>
          </tr>
        </thead>
        <tbody>
          <% @pictures.each do |picture| %>
            <tr>
              <td style="text-align: center;"><%= link_to image_tag(picture.image.url(:thumb), :style => 'max-height: 50px;'), admin_picture_path(picture) %></td>
              <td><%= link_to truncate(picture.title, :length => 32), admin_picture_path(picture) %></td>
              <td><%= picture.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <% if can? :edit, Picture %><td class="icon"><%= icon_edit_link edit_admin_picture_path(picture) %></td><% end %>
              <% if can? :destroy, Picture %><td class="icon"><%= icon_delete_link admin_picture_path(picture) %></td><% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @pictures %>
  <% else %>
    <p class="lead"><%= t('messages.pictures.none') %></p>
  <% end %>
</div>
<script id="template-upload" type="text/x-tmpl">
  <div class="upload">
    {%=o.name%}
    <div class="progress progress-striped active">
      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
    </div>
  </div>
</script>

app/views/admin/pictures/new.html.erb
<div id="new-picture" class="admin-content">
  <%= render 'form' %>
</div>

app/views/admin/pictures/selector.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Select a picture</h4>
    </div>
    <div class="modal-body">
      <form id="picture-selector-search-form" class="form-inline">
        <div class="form-group">
          <label for="filter-by-title">Search: </label>
          <input type="text" class="form-control" id="filter-by-title" name="filter-by-text">
        </div>
      </form>
      <div id="picture-selector-pictures" class="row">
        <% @pictures.each do |picture| %>
          <div class="picture-selector-picture col-xs-6" data-picture-url="<%= picture.image.url %>" data-picture-title="<%= picture.title %>" data-picture-alt-text="<%= picture.alt_text %>" data-picture-caption="<%= picture.caption %>" data-picture-width="<%= picture.image_original_width %>" data-picture-height="<%= picture.image_original_height %>">
            <div class="thumbnail">
              <div class="image-wrap">
                <%= image_tag picture.image.url(:medium), :alt => picture.alt_text, :title => picture.title, :data => { 'url' => picture.image.url, 'picture-id' => picture.id.to_s } %>
              </div>
              <div class="caption">
                <h5><%= picture.title %></h5>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/pictures/show.html.erb
<div id="picture-<%= @picture.id %>" class="admin-content">
  <h2><%= t('pictures.show.title') %> <small><%= truncate(@picture.title, :length => 48) %></small></h2>
  <div class="clearfix">
    <%= link_to t('pictures.links.back_to_index'), admin_pictures_path, :class => 'btn btn-default' %>
    <% if can? :edit, Picture %><%= link_to t('pictures.edit.title'), edit_admin_picture_path(@picture), :class => 'btn btn-primary' %><% end %>
    <% if can? :destroy, Picture %><%= link_to t('pictures.delete.title'), admin_picture_path(@picture), :method => 'delete', :class => 'btn btn-danger', :data => { :confirm => t('confirm_delete') } %><% end %>
  </div>
  <h3><%= t('pictures.sections.information') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
        <tr>
          <th class="col-xs-4 col-sm-2">Preview</th>
          <td class="col-xs-8 col-sm-10"><%= link_to image_tag(@picture.image.url(:medium), :alt => @picture.alt_text), @picture.image.url, :target => '_blank' %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.title') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.title %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.alt_text') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.alt_text %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.caption') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.caption %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_file_name') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_file_name %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_content_type') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_content_type %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_file_size') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_file_size %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_fingerprint') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_fingerprint %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_original_width') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_original_width %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_original_height') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_original_height %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_medium_width') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_medium_width %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_medium_height') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_medium_height %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_thumb_width') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_thumb_width %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.image_thumb_height') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.image_thumb_height %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.created_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.picture.updated_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @picture.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="clearfix">
    <%= link_to t('pictures.links.back_to_index'), admin_pictures_path, :class => 'btn btn-default' %>
    <% if can? :edit, Picture %><%= link_to t('pictures.edit.title'), edit_admin_picture_path(@picture), :class => 'btn btn-primary' %><% end %>
    <% if can? :destroy, Picture %><%= link_to t('pictures.delete.title'), admin_picture_path(@picture), :method => 'delete', :class => 'btn btn-danger', :data => { :confirm => t('confirm_delete') } %><% end %>
  </div>
</div>