config/routes.rb
Ruthieonart::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :passwords, :registrations, :confirmations, :unlocks]

  devise_scope :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session

    post 'update-password' => 'devise/passwords#create', :as => :user_password
    get 'reset-password' => 'devise/passwords#new', :as => :new_user_password
    get 'update-password' => 'devise/passwords#edit', :as => :edit_user_password
    put 'update-password' => 'devise/passwords#update'
  end

  get '/contact' => 'contact#new', :as => :contact

  post '/contact' => 'contact#create'

  resources :pages, :only => [:show]

  resources :posts, :only => [:show]

  get '/posts.rss' => 'posts#index', :format => :rss

  get '/sitemap.xml' => 'sitemap#index', :as => :sitemap, :format => :xml

  authenticate :user do
    namespace :admin do
      root :to => 'admin#index'

      resource :account, :only => [:show, :edit, :update]

      resources :pages

      resources :pictures do
        collection do
          get :selector
        end
      end

      resources :posts

      resources :users

      get '/tags.json' => 'tags#index'
    end

    post 'versions/:id/revert' => 'versions#revert', :as => :revert_version
  end

  root :to => 'posts#index'

  get ':id' => 'pages#show'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :role, :first_name, :last_name, :remember_me

  has_paper_trail :only => [:email, :role, :first_name, :last_name]

  has_many :posts, :dependent => :destroy

  validates_format_of     :email, :with => Devise.email_regexp, :allow_blank => true
  validates_presence_of   :email
  validates_uniqueness_of :email, :case_sensitive => false, :allow_blank => true

  validates_confirmation_of :password
  validates_length_of       :password, :within => 6..255, :if => :password_required?
  validates_presence_of     :password, :if => :password_required?

  validates_inclusion_of :role, :in => Ability::ROLES.map { |key, value| value }
  validates_presence_of  :role

  validates_length_of   :first_name, :maximum => 255
  validates_presence_of :first_name

  validates_length_of   :last_name, :maximum => 255
  validates_presence_of :last_name

  after_initialize do
    if self.new_record?
      self.email ||= ''
      self.encrypted_password ||= ''
      self.role ||= ''
      self.first_name ||= ''
      self.last_name ||= ''
      self.sign_in_count ||= 0
    end
  end

  before_save :define_role

  Ability::ROLES.each do |k, v|
    class_eval %Q"scope :#{k.to_s.pluralize}, where(:role => Ability::ROLES[:#{k.to_s}].downcase)"
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def short_name
    "#{self.first_name.first.upcase}. #{self.last_name}"
  end

  Ability::ROLES.each do |k, v|
    define_method("#{k.to_s}?") do
      self.role == k.to_s
    end

    define_method("#{k.to_s}!") do
      self.role = k.to_s
    end
  end

  def ability
    @ability ||= Ability.new(self)
  end

  protected

  def password_required?
    !self.persisted? || !self.password.blank? || !self.password_confirmation.blank?
  end

  def define_role
    self.role = Ability::ROLES.include?(role.downcase.to_sym) ? role.downcase : Ability::ROLES[:read_only]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_filter :authenticate_user!

  authorize_resource

  def index
    @search = User.search(params[:q])

    @users = @search.result.page(params[:page]).per(25).order('`users`.`last_name` ASC')
  end

  def show
    @user = User.where(:id => params[:id]).first

    if @user.nil?
      flash[:error] = t('messages.users.could_not_find')

      redirect_to admin_users_url
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:success] = t('messages.users.created')

      if params[:redirect_to_new].present?
        redirect_to new_admin_user_url
      else
        redirect_to admin_users_url
      end
    else
      flash[:error] = @user.errors.full_messages.uniq.join('. ') + '.'

      render 'new'
    end
  end

  def edit
    @user = User.where(:id => params[:id]).first

    if @user.nil?
      flash[:error] = t('messages.users.could_not_find')

      redirect_to admin_users_url
    end
  end

  def update
    @user = User.where(:id => params[:id]).first

    if @user.nil?
      flash[:error] = t('messages.users.could_not_find')

      redirect_to admin_users_url and return
    end

    if @user.update_attributes(params[:user])
      flash[:success] = t('messages.users.updated')

      redirect_to edit_admin_user_url(@user)
    else
      flash[:error] = @user.errors.full_messages.uniq.join('. ') + '.'

      render 'edit'
    end
  end

  def destroy
    @user = User.where(:id => params[:id]).first

    if @user.nil?
      flash[:error] = t('messages.users.could_not_find')

      redirect_to admin_users_url and return
    end

    @user.destroy

    flash[:success] = t('messages.users.deleted')

    redirect_to admin_users_url
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<h2><%= t("users.#{@user.persisted? ? 'edit' : 'new'}.title") %></h2>
<%= simple_form_for [:admin, @user], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :role, :as => :select, :collection => Ability.valid_roles(current_user).map { |key, value| [value.titleize, value] } %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= link_to t('users.links.back_to_index'), admin_users_path, :class => 'btn btn-default' %>
      <%= f.button :submit, 'Submit', :class => 'btn btn-primary' %>
      <% unless @user.persisted? %>
        <label for="redirect_to_new">
          <%= check_box_tag 'redirect_to_new', 1, true %> <%= t('helpers.submit.user.redirect_to_new') %>
        </label>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div id="edit-user" class="admin-content">
  <%= render 'form' %>
</div>

app/views/admin/users/index.html.erb
<div id="users" class="admin-content">
  <h2>
    <%= t('activerecord.models.user').pluralize %>
  </h2>
  <div class="well">
    <%= search_form_for @search, :url => admin_users_path, :html => { :method => :get, :class => 'form-inline' } do |f| %>
      <div class="form-group">
        <%= f.text_field :first_name_or_last_name_cont, :class => 'form-control', :placeholder => t('activerecord.attributes.user.full_name') %>
      </div>
      <div class="form-group">
        <%= f.text_field :email_cont, :class => 'form-control', :placeholder => t('activerecord.attributes.user.email') %>
      </div>
      <div class="form-group">
        <%= f.select :role_eq, Ability::ROLES.map { |key, value| [value.titleize, value] }, { :include_blank => "Select #{t('activerecord.attributes.user.role')}" }, { :class => 'form-control' } %>
      </div>
      <%= f.button '<span class="glyphicon glyphicon-search"></span> Search'.html_safe, :type => :submit, :class => 'btn btn-primary' %>
      <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, admin_users_path, :class => 'btn btn-default', :rel => 'tooltip', :title => t('clear_search') %>
    <% end %>
  </div>
  <% if can? :create, User %>
    <div class="clearfix">
      <%= link_to t('users.new.title'), new_admin_user_path, :class => 'btn btn-primary pull-right' %>
    </div>
  <% end %>
  <% if @users.any? %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th><%= sort_link @search, :last_name, t('activerecord.attributes.user.full_name') %></th>
            <th><%= sort_link @search, :email %></th>
            <th><%= sort_link @search, :role %></th>
            <th><%= sort_link @search, :created_at %></th>
            <% if can? :edit, User %><th class="icon">&nbsp;</th><% end %>
            <% if can? :destroy, User %><th class="icon">&nbsp;</th><% end %>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.full_name, admin_user_path(user) %></td>
              <td><%= user.email %> <%= link_to '<span class="glyphicon glyphicon-envelope">'.html_safe, "mailto:#{user.email}", :rel => 'tooltip', :title => 'Send Email' %></td>
              <td><%= user.role.titleize %></td>
              <td><%= user.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <% if can? :edit, user %><td class="icon"><%= icon_edit_link edit_admin_user_path(user) %></td><% elsif can? :update, User %><td>&nbsp;</td><% end %>
              <% if can? :destroy, user %><td class="icon"><%= icon_delete_link admin_user_path(user) %></td><% elsif can? :destroy, User %><td>&nbsp;</td><% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @users %>
  <% else %>
    <p class="lead"><%= t('messages.users.none') %></p>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<div id="new-user" class="admin-content">
  <%= render 'form' %>
</div>

app/views/admin/users/show.html.erb
<div id="user-<%= @user.id %>" class="admin-content">
  <h2><%= t('users.show.title') %> <small><%= @user.full_name %></small></h2>
  <div class="clearfix">
    <%= link_to t('users.links.back_to_index'), admin_users_path, :class => 'btn btn-default' %>
    <% if can? :edit, User %><%= link_to t('users.edit.title'), edit_admin_user_path(@user), :class => 'btn btn-primary' %><% end %>
    <% if can? :destroy, User %><%= link_to t('users.delete.title'), admin_user_path(@user), :method => 'delete', :class => 'btn btn-danger', :data => { :confirm => t('confirm_delete') } %><% end %>
  </div>
  <h3><%= t('users.sections.contact_information') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.first_name') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.first_name %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.last_name') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.last_name %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <h3><%= t('users.sections.account_information') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.email') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.email %> <%= link_to '<span class="glyphicon glyphicon-envelope">'.html_safe, "mailto:#{@user.email}", :rel => 'tooltip', :title => 'Send Email' %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.role') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.role.titleize %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.created_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.updated_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <h3><%= t('users.sections.login_activity') %></h3>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <tbody>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.sign_in_count') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.sign_in_count %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.current_sign_in_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.current_sign_in_at.blank? ? t('na') : @user.current_sign_in_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.last_sign_in_at') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.last_sign_in_at.blank? ? t('na') : @user.last_sign_in_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.current_sign_in_ip') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.current_sign_in_ip.blank? ? t('na') : @user.current_sign_in_ip %></td>
        </tr>
        <tr>
          <th class="col-xs-4 col-sm-2"><%= t('activerecord.attributes.user.last_sign_in_ip') %></th>
          <td class="col-xs-8 col-sm-10"><%= @user.last_sign_in_ip.blank? ? t('na') : @user.last_sign_in_ip %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="clearfix">
    <%= link_to t('users.links.back_to_index'), admin_users_path, :class => 'btn btn-default' %>
    <% if can? :edit, User %><%= link_to t('users.edit.title'), edit_admin_user_path(@user), :class => 'btn btn-primary' %><% end %>
    <% if can? :destroy, User %><%= link_to t('users.delete.title'), admin_user_path(@user), :method => 'delete', :class => 'btn btn-danger', :data => { :confirm => t('confirm_delete') } %><% end %>
  </div>
</div>